config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :straws
  resources :cup_toppings
  resources :teas
  resources :toppings, except: [:edit, :delete]
  resources :cups
  resources :users

  get '/login', to: 'auth#signin', as: 'signin'
  post '/login', to: 'auth#verify'
  delete '/login', to: 'auth#signout', as: 'signout'
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  get '/statistics', to: 'cups#statistics', as: 'statistics'
  # get '/bubbles/edit', to: 'cups#edit'
  # get '/choices', to: 'cups#size'
  # get '/create-tea', to: 'cups#new', as: 'new_cup'
  # post '/create-tea/:id', to: 'cups#create'
  # get '/all-my-teas', to: 'cups#index', as: 'cups'
  # get '/all-my-teas/:id', to: 'cups#show',as: 'cup'
  
    # resources :users


#within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cup.rb
class Cup < ApplicationRecord
    has_many :cup_toppings
    has_many :toppings, through: :cup_toppings
    belongs_to :tea
    belongs_to :user
    validates :name, presence: true

    
end

app/controllers/cups_controller.rb
class CupsController < ApplicationController
    # before_action :set_params, only: [:create, :update]
    # before_action :find_instance, only: :edit
    before_action :redirected_user
    # before_action :all_toppings, only: [:index, :show]

    def index
        if signed_in?
            @cups = Cup.all.select do |cup|
            cup.user_id == session[:user_id]
            end
        else
            redirect_to signin_path
        end
    end
    
    def new
        @cup = Cup.new
    end

    def create
        cup = params[:topping_ids].map do |topping|
            topping.to_i
        end
        params[:cup][:topping_ids] = cup.reverse
        params[:cup][:user_id] = session[:user_id]
        if params[:cup][:name].blank?
            params[:cup][:name] = "Unnamed Cup"
        end
        @cup = Cup.new(set_params)

        #this creates one instance of the topping associated witht he cup, then we will need tomultiple by amount for the other instances
    # byebug
        @cup.save
        # byebug
        #we are geting the amount of toppings instances just put into the cup
        length = params[:cup][:topping_ids].length

        total_toppings = params[:amount].map do |topping|
            topping.to_i
        end
        counter = 0
        temp = []
        while counter < length
            instance = Topping.all.find(@cup.topping_ids[total_toppings.length - counter - 1])
            (total_toppings[counter] - 1).times do
                temp << instance
                #instance of topping
            end
            counter += 1
        end
        @cup.toppings << temp


        #add functionality here to put bubbles
        #in cup in three layers, then take
        #a screenshot


        # byebug
        redirect_to cup_path(@cup)

    end

    def show
        @cup = Cup.find(params[:id])
        @tea = Tea.find(@cup.tea_id)
        if @cup.user_id == session[:user_id]
            @toppings = @cup.toppings
        else 
            flash[:error_message] = "You do not have view access to that cup."
            redirect_to cups_path
        end
    end

    def edit
        @cup = Cup.find(params[:id])
        if @cup.user_id != session[:user_id]
            flash[:error_message] = "You do not have edit access to that cup."
            redirect_to cups_path
        end
    end
    
    def update
        @cup = Cup.find_by(params[:id])
        @cup.update(set_params)
        redirect_to cup_path(@cup)
    end

    def destroy
        @cup = Cup.find(params[:id])
        if @cup.user_id != session[:user_id]
            flash[:error_message] = "You do not have edit access to that cup."
        else
            @cup.delete
        redirect_to cups_path
        end
    end

    def statistics
        @most_cups = User.find_by(username:User.most_cups_made)
        @most_recent = User.last.username
        @most_used_topping = Topping.find_by(name:Topping.most_used_topping)
        @tea = Tea.find_by(name:Tea.most_used_tea)
        render :statistics
    end

    private

    def set_params
        params.require(:cup).permit( :tea_id, :user_id, :name, :amount,  topping_ids: [])

    end

    # def tea_url
    #     @tea_url= find_instance.name
    # end

    #for purposes of associating amount to topping



    def find_instance
        @cup= Cup.first
    end






    # def all_toppings
    #     @all_cups= CupTopping.select do |cuptop|
    #         cuptop.cup_id == Cup.first.id
    #     end

    #     @all_topping= @all_cups.collect do |cups|
    #         cups.topping
    #     end

    #     @all_names= @all_topping.collect do |top|
    #         top.name
    #     end
    # end

end

app/helpers/cups_helper.rb
module CupsHelper
end

app/views/cups/edit.html.erb
<h1>Remaking Your BBT...</h1>

<h4>Edit your bubbles</h4>
<%# 
<h3><%= link_to 'Back to create', create_tea_path </h4>

<%=form_for @cup do |f|%>
        <p><%=f.label 'Tea'%>
        <%=f.collection_select :tea_id, Tea.all, :id, :name%></p>

        <%=f.label 'Straw Color'%>
        <%=f.collection_select :straw_id, Straw.all, :id, :color%>

<p><%=f.label :name%>
<%=f.text_field :name%></p>


<%=f.submit 'Edit Boba'%>
<br>
<br>
<br>
<%quote= Quote.rand_quote%><br>
<%="#{quote.quote} -#{quote.author}"%>

<%end%>

app/views/cups/index.html.erb
<%= flash[:error_message] %>
<div style="border-top:2px solid silver">
<br>
<h1>list of cup names</h1>



<ul style="list-style-type:circle;">
    <%@cups.each do |cup|%>
    <li><%=link_to 'View Cup', cup_path(cup), class: 'link-to-text-color'%>
    <%= cup.name%> </li>
    <%end%></ul>

<p><%= link_to 'Create New Tea', new_cup_path, class: 'link-to-text-color' %></p>
</div>

<br>
<br>
<br>
<br>
<br>

<br>
<br>

app/views/cups/new.html.erb
<%= stylesheet_link_tag "tea-fill.css" %>



<div align = "left" style="border-top:2px solid silver"><br>
<br>
<h1>Making Your BBT...</h1>



<%=form_for @cup do |f|%>
<%# <p><%=f.size :name%>
<p><%=f.label "Name your bubble tea!"%>
<%=f.text_field :name,:placeholder => "enter name", :id => "ip2"%></p>
        <%# <%=f.select :size, options_for_select(['Small', 'Medium', 'Large'])%>
        <p><%=f.label "tea type"%>

        <%=f.collection_select :tea_id, Tea.all, :id, :name%>
        <%#=f.label "straw Color"%>

        <%# <%=f.collection_select :straw_id, Straw.all, :id, :color%>
        <%# <br> %>

<%# <img src="https://cdn1.imggmi.com/uploads/2019/8/23/9c738052778c356752b23b17466a1071-full.png" style="width:400px;height:600px;left:20px;top:60px; position:absolute;"> %>

<img src="https://cdn1.imggmi.com/uploads/2019/8/23/9e2695b1f468b6218d937a7ab11da575-full.jpg"style="width:400px;height:600px;left:600px;top:60px; position:absolute;">
<br>

<h4>Pick your bubbles!</h4>

<%=f.label 'Bubble Amounts'%><br>



<%=f.collection_select :topping_ids, Topping.all, :id, :name ,{ multiple: true }, {:name => 'topping_ids[]'} %>
<%= f.select :amount, options_for_select(['1', '2', '3']), {multiple: true }, {:name => 'amount[]'}%><br>


<%=f.collection_select :topping_ids, Topping.all, :id, :name ,{ multiple: true }, {:name => 'topping_ids[]'} %>
<%= f.select :amount, options_for_select(['1', '2', '3']), {multiple: true }, {:name => 'amount[]'}%><br>

<%=f.collection_select :topping_ids, Topping.all, :id, :name ,{ multiple: true }, {:name => 'topping_ids[]'} %>
<%= f.select :amount, options_for_select([ '1', '2', '3']), {multiple: true }, {:name => 'amount[]'}%><br>

<%=f.collection_select :topping_ids, Topping.all, :id, :name , { multiple: true }, {:name => 'topping_ids[]'}%>
<%= f.select :amount, options_for_select(['1', '2', '3']), {multiple: true }, {:name => 'amount[]'}%><br>
<%=f.collection_select :topping_ids, Topping.all, :id, :name , { multiple: true }, {:name => 'topping_ids[]'}%>
<%= f.select :amount, options_for_select([ '1', '2', '3']), {multiple: true }, {:name => 'amount[]'}%><br>


<br>
<p><input class="btn btn-outline-secondary" type="submit" value="Create It"></p>
<br>
<br>
<br>
<%# save_screenshot(../../app/assets/images.png') %>


<%end%>

</div>

<br>

<br>
<br>
<br>

app/views/cups/show.html.erb
<%#= stylesheet_link_tag "tea-fill.css" %>
<%= stylesheet_link_tag "boba-fall.css" %>

<div>
<img src="https://cdn1.imggmi.com/uploads/2019/8/23/9e2695b1f468b6218d937a7ab11da575-full.jpg"style="width:750px;height:990px;left:900px;bottom:160px; position:absolute;">

</div>




<%i=@cup.toppings.length%>
<%temp=@cup.toppings%>

<div class = "stage1">

  <%if i<4%>
    <%@cup.toppings.each do |top|%>
      <figure class = "image1"></figure>
      <div class = "image1 bounce-7">
        <img class= "image1">
        src= "<%=top.img_url%>"
        alt="sam jackson">
      </div>
    <%end%>
  <%else%>
    <%x=0%>
        <figure class = "image1"></figure>
        <div class = "image1 bounce-7">
        <img class= "image1" src=" <%=@cup.toppings[x].img_url%>" alt="sam jackson">
        </div>
      <figure class = "image1"></figure>
      <div class = "image1 bounce-7">
      <img class= "image1" src=" <%=@cup.toppings[x+1].img_url%>" alt="sam jackson">
      </div>
      <figure class = "image1"></figure>
      <div class = "image1 bounce-7">
      <img class= "image1" src=" <%=@cup.toppings[x+2].img_url%>" alt="sam jackson">
      </div>
</div>

<div class= "stage2">
      <%x=3%>
      <figure class = "image1"></figure>
      <div class = "image1 bounce-7">
        <img class= "image1" src=" <%=@cup.toppings[x].img_url%>" alt="sam jackson">
      </div>
      <figure class = "image1"></figure>
      <div class = "image1 bounce-7">
        <img class= "image1" src=" <%=@cup.toppings[x+1].img_url%>" alt="sam jackson">
      </div>
      <figure class = "image1"></figure>
      <div class = "image1 bounce-7">
        <img class= "image1" src=" <%=@cup.toppings[x+2].img_url%>" alt="sam jackson">
      </div>

  </div>

<%end%>


   <div align = "left"> 
<details class = "details">
  <summary>Your Tea Facts: <%=@tea.name%></summary>
  <p> <%= @tea.description%></p>
  <p><%= @tea.origin%></p>
  <p><%= @tea.benefits%></p>
  </details>
</div>


<div align = "right" padding: 0px 30px>
<h1><%=@cup.name%></h1>
<h3>Current Toppings in your Cup</h3>



<%@toppings.each do |topping|%>
    <%=topping.name%><br>
    <div class = "memepics">
        <img src = <%=topping.img_url%> width="150" height="160"><br><br>
    </div>
<%end%>

</div>




<p><%= button_to 'Edit Cup', edit_cup_path(@cup), method: :get%></p>

<p><%= button_to 'Delete Cup', cup_path(@cup), method: :delete%></p>


<br>
<br>
<br>

app/views/cups/size.html.erb
# <h1>Pick your size</h1>

# <%=form_for Cup.first do |f|%>
# <%=f.select :size, options_for_select(['Small', 'Medium', 'Large'])%>
# <%=f.submit 'Pick size'%>

# <%=f.collection_select :tea_id, Tea.all, :id, :name%>
# <%=f.submit 'Pick tea'%>

# <%=f.collection_select :straw_id, Straw.all, :id, :color%>
# <%=f.submit 'Pick straw'%>

# <%end%>

app/views/cups/statistics.html.erb
<div align=center>
<br>

<h1> SITE STATS </h1>
<br>
<p>Most Cups Made: The user with the most cups is <font color="burlywood"><%=@most_cups.username%></font>, with <font color="burlywood"><%=@most_cups.cups.length%></font> cups!</p>

<p>Most Recent User: The most recently made user is <font color="burlywood"><%=@most_recent%></font>.</p>

<p>Most Used Topping: The most used topping is <font color="burlywood"><%=@most_used_topping.name%></font> which has been used <font color="burlywood"><%=@most_used_topping.cups.length%></font> times.</p>

<p>Most Used Tea: <font color="burlywood"><%=@tea.name%></font> has been used <font color="burlywood"><%=@tea.cups.length%></font> times.</p>
<details class = "details">
  <summary> Facts about <%=@tea.name%></summary>
  <p><%= @tea.description%></p>
  <p><%= @tea.origin%></p>
  <p><%= @tea.benefits%></p>
</details>





<br>
<br>
<p> Ellyn and Katana's, Mod 2 project </p>
<br>
</div>