config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :straws
  resources :cup_toppings
  resources :teas
  resources :toppings, except: [:edit, :delete]
  resources :cups
  resources :users

  get '/login', to: 'auth#signin', as: 'signin'
  post '/login', to: 'auth#verify'
  delete '/login', to: 'auth#signout', as: 'signout'
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  get '/statistics', to: 'cups#statistics', as: 'statistics'
  # get '/bubbles/edit', to: 'cups#edit'
  # get '/choices', to: 'cups#size'
  # get '/create-tea', to: 'cups#new', as: 'new_cup'
  # post '/create-tea/:id', to: 'cups#create'
  # get '/all-my-teas', to: 'cups#index', as: 'cups'
  # get '/all-my-teas/:id', to: 'cups#show',as: 'cup'
  
    # resources :users


#within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cup.rb
class Cup < ApplicationRecord
    has_many :cup_toppings
    has_many :toppings, through: :cup_toppings
    belongs_to :tea
    belongs_to :user
    validates :name, presence: true

    
end

app/models/cup_topping.rb
class CupTopping < ApplicationRecord
    belongs_to :cup
    belongs_to :topping
end

app/models/quote.rb
class Quote < ApplicationRecord
    validates :quote, uniqueness: true

    def self.rand_quote
        self.all[rand(self.count)]
    end


end

app/models/tea.rb
class Tea < ApplicationRecord
    has_many :cups

    def self.most_used_tea
        most_used_tea = ""
        tea = ""
        how_many_times = 0
        Tea.all.each do |tea|
            if tea.cups.length > how_many_times
                how_many_times = tea.cups.length
                most_used_tea = tea.name
            end
        end
        most_used_tea
    end

end

app/models/topping.rb
class Topping < ApplicationRecord
    has_many :cup_toppings
    has_many :cups, through: :cup_toppings
    validates :name, {presence: true, uniqueness: true}
    # validates :img_url, {presence: true, uniqueness: true}
    # validate :is_it_proper_pic
    # validates_format_of :img_url, :with => %r{\.(png|jpg|jpeg)$}i, :message => "whatever"

    def is_it_proper_pic
        if self.img_url.include?("jpg") || self.img_url.include?("png") || self.img_url.include?("jpeg")
            return true
        end
    end

    def self.most_used_topping
        most_used = ""
        amount_times_used = 0
        Topping.all.each do |topping|
            if topping.cup_toppings.length > amount_times_used
                amount_times_used = topping.cup_toppings.length
                most_used = topping.name
            end
        end
        return most_used
    end

    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :cups
    has_secure_password
    validates :username, :email, uniqueness: true, presence: true

    def self.most_cups_made
        most_cups = ""
        length = 0
        User.all.each do |user|
            if user.cups.length > length
                most_cups = user.username
                length = user.cups.length
            end
        end
        most_cups
    end


end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    def signin
    end
    
    def verify
    @user = User.find_by(username: params[:login][:username])
        if @user && @user.authenticate(params[:login][:password])
            session[:user_id] = @user.id
            redirect_to cups_path
        else
            flash[:error_message] = "Wrong login info. Try again."
            render :signin
        end
    end

    def signout
        session.clear
        redirect_to signin_path
    end
end

app/controllers/cups_controller.rb
class CupsController < ApplicationController
    # before_action :set_params, only: [:create, :update]
    # before_action :find_instance, only: :edit
    before_action :redirected_user
    # before_action :all_toppings, only: [:index, :show]

    def index
        if signed_in?
            @cups = Cup.all.select do |cup|
            cup.user_id == session[:user_id]
            end
        else
            redirect_to signin_path
        end
    end
    
    def new
        @cup = Cup.new
    end

    def create
        cup = params[:topping_ids].map do |topping|
            topping.to_i
        end
        params[:cup][:topping_ids] = cup.reverse
        params[:cup][:user_id] = session[:user_id]
        if params[:cup][:name].blank?
            params[:cup][:name] = "Unnamed Cup"
        end
        @cup = Cup.new(set_params)

        #this creates one instance of the topping associated witht he cup, then we will need tomultiple by amount for the other instances
    # byebug
        @cup.save
        # byebug
        #we are geting the amount of toppings instances just put into the cup
        length = params[:cup][:topping_ids].length

        total_toppings = params[:amount].map do |topping|
            topping.to_i
        end
        counter = 0
        temp = []
        while counter < length
            instance = Topping.all.find(@cup.topping_ids[total_toppings.length - counter - 1])
            (total_toppings[counter] - 1).times do
                temp << instance
                #instance of topping
            end
            counter += 1
        end
        @cup.toppings << temp


        #add functionality here to put bubbles
        #in cup in three layers, then take
        #a screenshot


        # byebug
        redirect_to cup_path(@cup)

    end

    def show
        @cup = Cup.find(params[:id])
        @tea = Tea.find(@cup.tea_id)
        if @cup.user_id == session[:user_id]
            @toppings = @cup.toppings
        else 
            flash[:error_message] = "You do not have view access to that cup."
            redirect_to cups_path
        end
    end

    def edit
        @cup = Cup.find(params[:id])
        if @cup.user_id != session[:user_id]
            flash[:error_message] = "You do not have edit access to that cup."
            redirect_to cups_path
        end
    end
    
    def update
        @cup = Cup.find_by(params[:id])
        @cup.update(set_params)
        redirect_to cup_path(@cup)
    end

    def destroy
        @cup = Cup.find(params[:id])
        if @cup.user_id != session[:user_id]
            flash[:error_message] = "You do not have edit access to that cup."
        else
            @cup.delete
        redirect_to cups_path
        end
    end

    def statistics
        @most_cups = User.find_by(username:User.most_cups_made)
        @most_recent = User.last.username
        @most_used_topping = Topping.find_by(name:Topping.most_used_topping)
        @tea = Tea.find_by(name:Tea.most_used_tea)
        render :statistics
    end

    private

    def set_params
        params.require(:cup).permit( :tea_id, :user_id, :name, :amount,  topping_ids: [])

    end

    # def tea_url
    #     @tea_url= find_instance.name
    # end

    #for purposes of associating amount to topping



    def find_instance
        @cup= Cup.first
    end






    # def all_toppings
    #     @all_cups= CupTopping.select do |cuptop|
    #         cuptop.cup_id == Cup.first.id
    #     end

    #     @all_topping= @all_cups.collect do |cups|
    #         cups.topping
    #     end

    #     @all_names= @all_topping.collect do |top|
    #         top.name
    #     end
    # end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
end

app/controllers/teas_controller.rb
class TeasController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def show
        if !set_user
            redirect_to signin_path
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to cups_path
        else 
            redirect_to signup_path
            flash[:error_message] = "The user "
        end
    end

    private 
    def user_params
        params.require(:user).permit(:username,:password_digest,:password,:name,:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cup_toppings_helper.rb
module CupToppingsHelper
end

app/helpers/cups_helper.rb
module CupsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/straws_helper.rb
module StrawsHelper
end

app/helpers/teas_helper.rb
module TeasHelper
end

app/helpers/toppings_helper.rb
module ToppingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BubbleTeaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "stylesheetkatana.css" %> 
    
    <%= stylesheet_link_tag "style.css" %>
    
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   
    

  </head>

  
  <div id='navbar' class="navbar navbar-expand-lg navbar-light bg-transparent">  
    
    <img src="https://cdn1.imggmi.com/uploads/2019/8/23/130f4542d48b227528069cbb95739f66-full.png" width="40" height="30" style = "padding-right: 10px" class="d-inline-block align-top" alt="">
    <a class="navbar-brand" <%=link_to 'BobaApp', statistics_path%>
  </a>
  
  <% if signed_in? %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" <%=link_to 'My Cups', cups_path%><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%=link_to 'Create A Cup', new_cup_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%=link_to 'Create A Topping', new_topping_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%=link_to 'Sign Out', signout_path, method: :delete%></a>
      </li>
      </ul>

<%else%>
  <span class="navbar-text" >

      Made with love by Ellyn and Katana
    </span>
    <%end%>
</div>
</nav>

<%# <nav class="navbar navbar-expand-lg navbar-light bg-transparent">


  <div class="collapse navbar-collapse" id="navbarSupportedContent"> %>
    
    <%# <a class="navbar-brand" href="">
<img src= "https://cdn1.imggmi.com/uploads/2019/8/23/9c738052778c356752b23b17466a1071-full.png"
 width="40" height="30" style = "padding-right: 10px" class="d-inline-block align-top" alt=""> %>
    



  <body>
    <%= yield %>
  </body>
  
 


<footer>

  <div class="navbar">
    <ul><%quote= Quote.rand_quote%><br>
    <%="#{quote.quote} - #{quote.author}"%></ul>
    <div align=left>
  <p><details>
    <summary>Copyright 2019.</summary>
    <p>- Created by Ellyn Anderson and Katana Tran. All Rights Reserved. </p>
  </details></p>
</div>
  </div>
  <iframe id="foot" src="https://open.spotify.com/embed/album/0S0KGZnfBGSIssfF54WSJh" width="100%" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media">
  </iframe>
</footer>
</html>